# Generated by Django 4.2 on 2023-05-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Booking_Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consignor', models.CharField(max_length=50)),
                ('Consignee', models.CharField(max_length=50)),
                ('From', models.CharField(max_length=50)),
                ('To', models.CharField(max_length=50)),
                ('LR_NO', models.CharField(max_length=50)),
                ('Invoice_No', models.CharField(max_length=50)),
                ('Vehicle_No', models.CharField(max_length=50)),
                ('Vehicle_Type', models.CharField(max_length=50)),
                ('Material', models.CharField(max_length=50)),
                ('Type_of_packaging', models.CharField(max_length=50)),
                ('Total_weight_of_material', models.CharField(max_length=50)),
                ('Rate_per_kg_or_station', models.CharField(max_length=50)),
                ('TPT', models.CharField(max_length=50)),
                ('PAN', models.CharField(max_length=50)),
                ('TDS_Exemption', models.CharField(max_length=50)),
                ('Balance_freight_to_be_paid', models.CharField(max_length=50)),
                ('NEFT_OR_CASH', models.CharField(max_length=50)),
                ('Accountno_BrokerName', models.CharField(max_length=50)),
                ('Bank_Name', models.CharField(max_length=50)),
                ('IFSC_CODE', models.CharField(max_length=50)),
                ('Remarks', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
