# Generated by Django 4.2 on 2023-05-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_vehicle_booking_statement_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Actual_Freight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Advance_Freight_Cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Advance_Freight_NEFT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Balance_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Bilty_Charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Booking_Freight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Broker_Transporter_Account_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Cash_To_Driver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='DetentionCharges_OverloadChallan_Tax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Detention_Charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Driver_Mobile_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Extra_Point_Charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Extra_Running_Charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Grand_Total_Booking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Hamali_Charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='LHC_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='LR_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='NEFT_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='No_Of_Boxes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='POD_Rcv_Dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Party_Due',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Party_Due_Other',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Placement_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Submitted_On',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Surplus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Surpluspercent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='TDS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='TDS_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='TDSpercent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Total_Due',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Total_Vehicle_Freight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Unloading_Paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Unloading_chargespaidtodriver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='other_Extra_Charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Accountno_BrokerName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Balance_freight_to_be_paid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Consignee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Consignor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='From',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='IFSC_CODE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Invoice_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='LR_NO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='NEFT_OR_CASH',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='PAN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Rate_per_kg_or_station',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='TDS_Exemption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='TPT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='To',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Total_weight_of_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Type_of_packaging',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Vehicle_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Vehicle_Type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
