# Generated by Django 4.2 on 2023-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_vehicle_booking_statement_actual_freight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='BillDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
