# Generated by Django 4.2 on 2023-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_vehicle_booking_statement_billdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=50)),
            ],
        ),
    ]
