# Generated by Django 4.2 on 2023-05-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_product_advance_freight_cash_product_billdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='BillNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
