# Generated by Django 4.2 on 2023-05-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_vehicle_booking_statement_billno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTH_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placement_Date', models.DateField(blank=True, null=True)),
                ('Consignor', models.CharField(blank=True, max_length=50, null=True)),
                ('Consignee', models.CharField(blank=True, max_length=50, null=True)),
                ('From', models.CharField(blank=True, max_length=50, null=True)),
                ('To', models.CharField(blank=True, max_length=50, null=True)),
                ('LR_NO', models.CharField(blank=True, max_length=50, null=True)),
                ('LR_DATE', models.DateField(blank=True, null=True)),
                ('Vehicle_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Vehicle_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Driver_Mobile_No', models.IntegerField(blank=True, null=True)),
                ('Material', models.CharField(blank=True, max_length=50, null=True)),
                ('LHC_No', models.IntegerField(blank=True, null=True)),
                ('Party_Due_Other', models.IntegerField(blank=True, null=True)),
                ('Cash_To_Driver', models.IntegerField(blank=True, null=True)),
                ('Advance_Freight_Cash', models.IntegerField(blank=True, null=True)),
                ('Advance_Freight_NEFT', models.IntegerField(blank=True, null=True)),
                ('DetentionCharges_OverloadChallan_Tax', models.IntegerField(blank=True, null=True)),
                ('Unloading_chargespaidtodriver', models.IntegerField(blank=True, null=True)),
                ('Balance', models.IntegerField(blank=True, null=True)),
                ('Total_Vehicle_Freight', models.IntegerField(blank=True, null=True)),
                ('TPT', models.CharField(blank=True, max_length=50, null=True)),
                ('PAN', models.CharField(blank=True, max_length=50, null=True)),
                ('TDS_Exemption', models.CharField(blank=True, max_length=50, null=True)),
                ('NEFT_Date', models.DateField(blank=True, null=True)),
                ('POD_Rcv_Dt', models.DateField(blank=True, null=True)),
                ('Balance_freight_to_be_paid', models.CharField(blank=True, max_length=50, null=True)),
                ('Balance_paid', models.IntegerField(blank=True, null=True)),
                ('Unloading_Paid', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('NEFT_OR_CASH', models.CharField(blank=True, max_length=50, null=True)),
                ('Accountno_BrokerName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
