# Generated by Django 4.2 on 2023-05-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_bth_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
