# Generated by Django 4.2 on 2023-05-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_No', models.IntegerField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Party_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('GSTIN_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Freight_Amount', models.FloatField(blank=True, null=True)),
                ('Others', models.FloatField(blank=True, null=True)),
                ('Total_Bill_Amount', models.FloatField(blank=True, null=True)),
                ('Bill_Submitted_On', models.DateField(blank=True, null=True)),
                ('Advance_Received_Amount', models.FloatField(blank=True, null=True)),
                ('Received_Amount', models.FloatField(blank=True, null=True)),
                ('Payment_Received_On', models.DateField(blank=True, null=True)),
                ('Short_Excess', models.FloatField(blank=True, null=True)),
                ('Reason', models.CharField(blank=True, max_length=200, null=True)),
                ('Today', models.DateField(blank=True, null=True)),
                ('Day', models.CharField(blank=True, max_length=50, null=True)),
                ('Remark', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
