# Generated by Django 4.2 on 2023-05-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_bill_reg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_booking_statement',
            old_name='BillNo',
            new_name='Bill_No',
        ),
    ]
