# Generated by Django 4.2 on 2023-05-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_rename_billno_vehicle_booking_statement_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='month',
            field=models.CharField(default=90, max_length=50),
            preserve_default=False,
        ),
    ]
