# Generated by Django 4.2 on 2023-05-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_tptpanmapping_transporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='tpt_pan_mapping',
        ),
        migrations.DeleteModel(
            name='TptPanMapping',
        ),
        migrations.DeleteModel(
            name='Transporter',
        ),
    ]
