# Generated by Django 4.2 on 2023-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_remove_transporter_tpt_pan_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_reg',
            name='sr_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
