# Generated by Django 4.2 on 2023-05-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_bill_reg_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_reg',
            name='Advance_Received_Amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Bill_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Bill_Submitted_On',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Freight_Amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Others',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Payment_Received_On',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Received_Amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Short_Excess',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Today',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='Total_Bill_Amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill_reg',
            name='sr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
