# Generated by Django 4.2 on 2023-05-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_vehicle_booking_statement_actual_freight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_booking_statement',
            name='Bill_No',
        ),
    ]
