# Generated by Django 4.2 on 2023-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_rename_bth_details_vehical_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Advance_Freight_Cash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Advance_Freight_NEFT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Balance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Balance_paid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Cash_To_Driver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='DetentionCharges_OverloadChallan_Tax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Driver_Mobile_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='LHC_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Party_Due_Other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Total_Vehicle_Freight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Unloading_Paid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehical_expenses',
            name='Unloading_chargespaidtodriver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
