# Generated by Django 4.2 on 2023-05-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_alter_vehical_expenses_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
