# Generated by Django 4.2 on 2023-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_alter_vehicle_booking_statement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
