# Generated by Django 4.2 on 2023-05-31 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_vehicle_booking_statement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LHC_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Party_Due_Other', models.CharField(blank=True, max_length=50, null=True)),
                ('Cash_To_Driver', models.CharField(blank=True, max_length=50, null=True)),
                ('Advance_Freight_Cash', models.CharField(blank=True, max_length=50, null=True)),
                ('Advance_Freight_NEFT', models.CharField(blank=True, max_length=50, null=True)),
                ('DetentionCharges_OverloadChallan_Tax', models.CharField(blank=True, max_length=50, null=True)),
                ('Unloading_chargespaidtodriver', models.CharField(blank=True, max_length=50, null=True)),
                ('Balance', models.CharField(blank=True, max_length=50, null=True)),
                ('Total_Vehicle_Freight', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_booking_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.vehicle_booking_statement')),
            ],
        ),
        migrations.CreateModel(
            name='Outstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_Freight', models.CharField(blank=True, max_length=50, null=True)),
                ('Party_Due', models.CharField(blank=True, max_length=50, null=True)),
                ('Total_Due', models.CharField(blank=True, max_length=50, null=True)),
                ('Bilty_Charge', models.CharField(blank=True, max_length=50, null=True)),
                ('Extra_Point_Charge', models.CharField(blank=True, max_length=50, null=True)),
                ('Extra_Running_Charge', models.CharField(blank=True, max_length=50, null=True)),
                ('Detention_Charge', models.CharField(blank=True, max_length=50, null=True)),
                ('Hamali_Charge', models.CharField(blank=True, max_length=50, null=True)),
                ('other_Extra_Charge', models.CharField(blank=True, max_length=50, null=True)),
                ('Grand_Total_Booking', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_booking_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.vehicle_booking_statement')),
            ],
        ),
    ]
