# Generated by Django 4.2 on 2023-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_vehicle_expenses_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='POD',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
