# Generated by Django 4.2 on 2023-06-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_vehicle_booking_statement_pod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outstanding',
            old_name='Bilty_Charge',
            new_name='Party_Name',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='Booking_Freight',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='Detention_Charge',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='Extra_Point_Charge',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='Extra_Running_Charge',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='Grand_Total_Booking',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='Hamali_Charge',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='Party_Due',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='Total_Due',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='other_Extra_Charge',
        ),
        migrations.RemoveField(
            model_name='outstanding',
            name='vehicle_booking_statement',
        ),
        migrations.AddField(
            model_name='outstanding',
            name='Bill_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outstanding',
            name='Days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outstanding',
            name='Freight_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outstanding',
            name='LR_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outstanding',
            name='Payment_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outstanding',
            name='Received_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outstanding',
            name='Total_Bill_Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
