# Generated by Django 4.2 on 2023-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_rename_bilty_charge_outstanding_party_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstanding',
            name='Bill_SubOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outstanding',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outstanding',
            name='Received_on_dt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
