# Generated by Django 4.2 on 2023-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_outstanding_bill_subon_outstanding_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstanding',
            name='POD_Received',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3, null=True),
        ),
    ]
