# Generated by Django 4.2 on 2023-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_outstanding_pod_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstanding',
            name='Bill_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outstanding',
            name='Freight_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outstanding',
            name='LR_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='outstanding',
            name='Total_Bill_Amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
