# Generated by Django 4.2 on 2023-06-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_alter_outstanding_bill_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstanding',
            name='POD_Received',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
