# Generated by Django 4.2 on 2023-06-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_alter_outstanding_pod_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='outstanding',
            name='Consignor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outstanding',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
