# Generated by Django 4.2 on 2023-06-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_remove_outstanding_id_alter_outstanding_bill_subon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle_Expenses',
        ),
    ]
