# Generated by Django 4.2 on 2023-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0033_delete_vehicle_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('12', 'December')], max_length=2, null=True),
        ),
    ]
