# Generated by Django 4.2 on 2023-06-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_alter_outstanding_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_booking_statement',
            name='Remarks1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
