# Generated by Django 4.2 on 2023-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0039_vehicle_booking_statement_remarks1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='BillDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='NEFT_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Placement_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_booking_statement',
            name='Submitted_On',
            field=models.DateField(blank=True, null=True),
        ),
    ]
