# Generated by Django 4.2 on 2023-08-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0044_delete_party_remove_profit_business_delete_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutstandingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SR_No', models.PositiveIntegerField()),
                ('Party_Name', models.CharField(max_length=50)),
                ('Bill_No', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Freight_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Less_TDS', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Total_Bill_Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Bill_sub_on', models.DateField()),
            ],
        ),
    ]
